-- PR #59 proof schema only. Do not apply to production until the queue worker is reviewed.
create table if not exists public.national_rain_refinement_jobs (
  id bigint generated by default as identity primary key,
  run_key text not null,
  basetime timestamptz not null,
  validtime timestamptz not null,
  zoom integer not null default 8 check (zoom between 0 and 18),
  tile_x integer not null,
  tile_y integer not null,
  priority integer not null default 0,
  status text not null default 'PENDING' check (status in ('PENDING','PROCESSING','DONE','FAILED')),
  attempts integer not null default 0 check (attempts >= 0),
  available_at timestamptz not null default now(),
  claimed_at timestamptz,
  completed_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (run_key, validtime, zoom, tile_x, tile_y)
);

create index if not exists national_rain_refinement_jobs_pending_idx
  on public.national_rain_refinement_jobs (status, available_at, priority desc, validtime, id);

comment on table public.national_rain_refinement_jobs is
  'Internal queue for nationwide heavy-rain high-resolution refinement. Separate from per-user watch_targets.';
