-- PR #59 proof schema only. Do not apply to production until the queue worker is reviewed.
create table if not exists public.national_rain_refinement_jobs (
  id bigint generated by default as identity primary key,
  run_key text not null,
  basetime timestamptz not null,
  validtime timestamptz not null,
  zoom integer not null default 8 check (zoom between 0 and 18),
  tile_x integer not null,
  tile_y integer not null,
  priority integer not null default 0,
  status text not null default 'PENDING' check (status in ('PENDING','PROCESSING','DONE','FAILED')),
  attempts integer not null default 0 check (attempts >= 0),
  available_at timestamptz not null default now(),
  claimed_at timestamptz,
  completed_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (run_key, validtime, zoom, tile_x, tile_y)
);

create table if not exists public.national_rain_refinement_results (
  job_id bigint primary key references public.national_rain_refinement_jobs(id) on delete cascade,
  run_key text not null,
  basetime timestamptz not null,
  validtime timestamptz not null,
  zoom integer not null,
  tile_x integer not null,
  tile_y integer not null,
  strong_pixel_count integer not null default 0 check (strong_pixel_count >= 0),
  footprint jsonb not null default '[]'::jsonb,
  municipalities jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (run_key, validtime, zoom, tile_x, tile_y)
);

comment on table public.national_rain_refinement_results is
  'High-resolution nationwide rain refinement proof results. footprint stores bounded strong-rain geometry and municipalities stores N03 intersections. Not connected to watch_targets or push notifications.';

create index if not exists national_rain_refinement_results_time_idx
  on public.national_rain_refinement_results (validtime, run_key);

create index if not exists national_rain_refinement_jobs_pending_idx
  on public.national_rain_refinement_jobs (status, available_at, priority desc, validtime, id);

comment on table public.national_rain_refinement_jobs is
  'Internal queue for nationwide heavy-rain high-resolution refinement. Separate from per-user watch_targets.';


create or replace function public.claim_national_rain_refinement_jobs(p_limit integer default 20)
returns setof public.national_rain_refinement_jobs
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with picked as (
    select id
    from public.national_rain_refinement_jobs
    where ((status = 'PENDING' and available_at <= now())
        or (status = 'PROCESSING' and claimed_at <= now() - interval '5 minutes'))
      and attempts < 5
    order by priority desc, validtime, id
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 20), 100))
  )
  update public.national_rain_refinement_jobs j
  set status = 'PROCESSING',
      attempts = j.attempts + 1,
      claimed_at = now(),
      updated_at = now()
  from picked
  where j.id = picked.id
  returning j.*;
end;
$$;

create or replace function public.finish_national_rain_refinement_job(
  p_id bigint,
  p_success boolean,
  p_error text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.national_rain_refinement_jobs
  set status = case
        when p_success then 'DONE'
        when attempts >= 5 then 'FAILED'
        else 'PENDING'
      end,
      completed_at = case when p_success or attempts >= 5 then now() else null end,
      available_at = case when p_success or attempts >= 5 then available_at else now() + interval '1 minute' end,
      last_error = case when p_success then null else left(coalesce(p_error, 'unknown_error'), 2000) end,
      updated_at = now()
  where id = p_id
    and status = 'PROCESSING';
end;
$$;

revoke all on function public.claim_national_rain_refinement_jobs(integer) from public, anon, authenticated;
revoke all on function public.finish_national_rain_refinement_job(bigint, boolean, text) from public, anon, authenticated;
grant execute on function public.claim_national_rain_refinement_jobs(integer) to service_role;
grant execute on function public.finish_national_rain_refinement_job(bigint, boolean, text) to service_role;


create or replace function public.defer_national_rain_refinement_job(p_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.national_rain_refinement_jobs
  set status = 'PENDING',
      attempts = greatest(attempts - 1, 0),
      claimed_at = null,
      available_at = now(),
      last_error = null,
      updated_at = now()
  where id = p_id
    and status = 'PROCESSING';
end;
$$;

revoke all on function public.defer_national_rain_refinement_job(bigint) from public, anon, authenticated;
grant execute on function public.defer_national_rain_refinement_job(bigint) to service_role;
